

[default]
binary = false
check-filename = false

[default.extend-words]
clen = "clen"
nd = "nd"
fo = "fo"
slac = "slac"
lod = "lod"
ba = "ba"
mis = "mis"
nax = "nax"
LIK = "LIK"
AKE = "AKE"
som = "som"
ags = "ags"
nin = "nin"
ARTIC = "ARTIC"
formate = "formate"
repid = "repid"
Spred = "Spred"
pilon = "pilon"
cellpading = "cellpading"
daa = "daa"
recal = "recal"
Ser = "Ser"
syringae = "syringae"
ACN = "ACN"
CLL = "CLL"
BLOSUM = "BLOSUM"
Mch = "Mch"
fof = "fof"
RABIT = "RABIT"
Tiggers = "Tiggers"
Tigger = "Tigger"
hda = "hda"
tre = "tre"
ANC = "ANC"
hsa = "hsa"
SLAC = "SLAC"
Tpos = "Tpos"
Lates = "Lates"
OTU = "OTU"
PN = "PN"
OT = "OT"
WARNIN = "WARNIN"
ERRO = "ERRO"
COMMET = "COMMET"
LOD = "LOD"
ABD = "ABD"
Ffrom = "Ffrom"
BA = "BA"
NED = "NED"
Pase = "Pase"
ALPH = "ALPH"
gost = "gost"
thr = "thr"
hom = "hom"
MULTICAT = "MULTICAT"
WNT = "WNT"
dropse = "dropse"
rror = "rror"
Holliday = "Holliday"
tbe = "tbe"
NAST = "NAST"
gard = "gard"
nwo = "nwo"
Ture = "Ture"

## might be a typo in embl tools...change to best?
Ebst = "Ebst"
## might be a real typo, strat->start
strat = "strat"
